In [1]:
import os
import numpy as np
import pandas as pd
import polars as pl

In [2]:
!pwd

/home/vanishhhed/Desktop/codics/PythonCodics/tenderhack/ML/src/data

In [2]:
cte_df = pd.read_excel("../../data/raw/TenderHack_СТЕ_20260313.xlsx")
contracts_df = pd.read_excel("../../data/raw/TenderHack_Контракты_20260313.xlsx")

In [4]:
cte_df

,Идентификатор СТЕ,Наименование СТЕ,Категория,Производитель,характеристики СТЕ,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,34863000,Мусорные пакеты 35л,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,"Количество в упаковке:30.00000;Толщина, мкм:50...",NaN,NaN,NaN,NaN,NaN,NaN
1,20647780,Пакеты для мусора,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,Цвет:черный;Ширина:470.00000;Количество рулоно...,NaN,NaN,NaN,NaN,NaN,NaN
2,34865337,Мусорные пакеты 240л,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,Количество в упаковке:10.00000;Цвет:черный;Тол...,NaN,NaN,NaN,NaN,NaN,NaN
3,38669978,"Радиостанция носимая аналоговая Шеврон, ""АЙТИ-...",Радиостанции цифровые,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АЙТИ...",Максимальная рабочая температура:50.00000;Коли...,NaN,NaN,NaN,NaN,NaN,NaN
4,38515747,Набор реагентов для иммуноферментного определе...,Наборы реактивов/реагентов,"ООО ""ХЕМА""",Концентрация аналита в наибольшей калибровочно...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244487,39163435,Гофра для раковины EWRIKA 85001 85036-750 40 м...,Удлинители гофрированные для оборудования сант...,EWRIKA,Ширина:65.00000;Комплектация:Комплект прокладо...,NaN,NaN,NaN,NaN,NaN,NaN
244488,39163497,"Творог Б.Ю. Александров 9%, 180г",Творог,Б.Ю. АЛЕКСАНДРОВ,Наличие вкусовых компонентов:Нет;Вид молочного...,NaN,NaN,NaN,NaN,NaN,NaN
244489,39165297,"Труба VALFEX OPTIMA ф110, с раструбом, L=0.25 ...",Детали и фитинги трубопроводов из полимеров,VALFEX OPTIMA,Материал трубы:полипропилен;Вид товара:Труба;Д...,NaN,NaN,NaN,NaN,NaN,NaN
244490,1374499,Мука пшеничная Макфа весовая,Мука пшеничная хлебопекарная,"АО ""Макфа""",Назначение:пшеничная хлебопекарная;Тарная упак...,NaN,NaN,NaN,NaN,NaN,NaN
244491,23651430,Устройство для клеймения шин Ш-309,Приборы для клеймения (маркировки) шин,ООО«ТехСервисСнаб»,Температура поверхности клейма:550-600 °С;Вес:...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
contracts_df

,Наименование закупки,Количество,Единица измерения,Идентификатор контракта,Способ закупки,Начальная стоимость контракта,Стоимость контракта после заключения,% снижения,Ставка НДС,Дата заключения контракта,...,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Поставка товара,2.0,шт,205193314,Контракт по итогам прямой закупки,25940.00,25940.00,0.000000,20%,2025-01-15 07:46:00.660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461438,Поставка запасных частей для системы вентиляци...,1.0,шт,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461439,Поставка запасных частей для системы вентиляци...,5.0,шт,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461440,Поставка баков для воды для обеспечения готов...,212.0,шт,213291692,Контракт по итогам котировочной сессии,585756.00,582826.16,0.500181,Без НДС,2025-12-30 00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461441,Поставка тележек и контейнеров для сбора мусора,20.0,шт,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461442,Поставка тележек и контейнеров для сбора мусора,20.0,шт,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cte_df.columns

Index(['Идентификатор СТЕ', 'Наименование СТЕ', 'Категория', 'Производитель',
       'характеристики СТЕ', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'],
      dtype='object')

In [8]:
cols = ['Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']  # нужные колонки

mask = cte_df[cols].notna().any(axis=1)
error_cte = cte_df[mask]
error_cte

,Идентификатор СТЕ,Наименование СТЕ,Категория,Производитель,характеристики СТЕ,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
158119,38695683,Трость для бас кларнета Vandoren V12 №4 CR624,Принадлежности для духовых музыкальных инструм...,Vandoren\tМатериал:Тростник;Принадлежность:Бас...,Принадлежности для духовых музыкальных инструм...,Vandoren\tВид духового инструмента:Кларнет;Ком...,Принадлежности для духовых музыкальных инструм...,Vandoren\tВид товаров:Товары для учреждений ку...,Толщина кончика:0.30000;Вес:7.00000;Материал:Т...,NaN,NaN
158191,38697059,Лигатура для кларнета in es Vandoren Оptimum L...,Принадлежности для духовых музыкальных инструм...,Vandoren\tМатериал:Металл;Назначение:для кларн...,Системное программное обеспечение,ИП Кузнецов Александр Александрович,Гарантийный срок:1;Вид лицензии:Лицензионный к...,NaN,NaN,NaN,NaN
175722,36490431,"Клинок, тип ""Макинтош"" №4, принадлежность для ...",Рукоятки,KIRCHNER \tДиаметр фиброоптического световода:...,Рукоятки,KIRCHNER \tИспользование:Многократное;Длина:15...,Рукоятки,KIRCHNER \tВысота:25;Длина клинка:155;Материал...,Рукоятки,KIRCHNER \tВид товаров:Медицинские товары;Тип ...,Тип замка рукояти:Клик;Диаметр рукояти:28;Тип ...
175724,38087575,Неврологический набор для диагностики диабетич...,"Составные и заменяемые части, принадлежности и...","KIRCHNER \tМатериал:пластик, металл;Вид товары...",Карандаши чернографитные,Koh-i-Noor,Материал корпуса:Дерево;Заточенный:1;Твердость...,NaN,NaN,NaN,NaN
193177,36236406,Фонарь светодиодный КОСМОС KOC860LED 19хLED,Приборы бытовые осветительные с питанием от ба...,"KENNEDE ELECTRONICS MFG. CO., LTD.\tМатериал к...",Виброплиты,"ООО ""Техуборка""",Вид стартера:Ручной;Тип виброплиты:Реверсивная...,NaN,NaN,NaN,NaN
231185,38531226,"Шоколад молочный ""O'Zera» Double Milk & Whit...",Шоколад в упакованном виде,O'Zera»\tВид товаров:Пищевые продукты;Вид шоко...,Комплексы многофункциональные интерактивные уч...,ОООО ТД Редвинс,Виды комплексов многофункциональных учебных:Ко...,NaN,NaN,NaN,NaN

In [ ]:
rows_to_drop = error_cte["Идентификатор СТЕ"].to_list()
cte_df = cte_df[~cte_df["Идентификатор СТЕ"].isin(rows_to_drop)]

for col in ['Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']:
    print(cte_df[col].unique())

In [16]:
cte_df.drop(columns=['Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'], inplace=True)

/tmp/ipykernel_15003/4241461968.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cte_df.drop(columns=['Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'], inplace=True)

In [18]:
cte_df = cte_df.rename(columns={
    'Идентификатор СТЕ': "CTE_id", 
    'Наименование СТЕ': "CTE_name",
    'Категория': "category",
    'Производитель': "manufacturer",
    'характеристики СТЕ': "characteristics"
})

In [28]:
cte_nan = cte_df[cte_df.isna().any(axis=1)]
cte_nan

,CTE_id,CTE_name,category,manufacturer,characteristics
49727,34832677,Эмаль Ярославские краски ПФ-115 глянцевая цвет...,Тип тары (потребительская упаковка):банка жест...,NaN,NaN
165400,39114363,"Ненасыщенная железосвязывающая способность, ре...",Реагенты и расходные материалы для анализаторо...,"Бекмен Культер, Инк.\tВид реагенты и расходные...",NaN
220702,38163960,"Стакан лабораторный высокий В-1-50, 50 мл, с н...",Материал:стекло;Высота:75;Диаметр:36;Объем:50,NaN,NaN
239491,36715295,"Диск Алмазный ""torgwin"" асфальт 500мм",Диски для пил циркулярных,torgwin\tВнутренний диаметр:500.00000;Вид диск...,NaN

In [37]:
for cte_id in [39114363, 36715295]:
    mask = cte_df["CTE_id"] == cte_id
    cte_df.loc[mask, "characteristics"] = (
        cte_df.loc[mask, "manufacturer"]
        .astype(str)
        .apply(lambda x: x.split("\t")[1])
    )
    cte_df.loc[mask, "manufacturer"] = (
        cte_df.loc[mask, "manufacturer"]
        .astype(str)
        .apply(lambda x: x.split("\t")[0])
    )

In [41]:
cte_df.dropna(inplace=True)
print(cte_df.shape)

(244484, 5)

In [48]:
print(f"Duplicates: {cte_df.shape[0] - cte_df['CTE_id'].nunique()}")

Duplicates: 0

In [ ]:
cte_df.head()
cte_df.to_csv("../../data/prep/CTE.csv", index=False)

In [3]:
contracts_df.columns

Index(['Наименование закупки', 'Количество', 'Единица измерения',
       'Идентификатор контракта', 'Способ закупки',
       'Начальная стоимость контракта', 'Стоимость контракта после заключения',
       '% снижения', 'Ставка НДС', 'Дата заключения контракта',
       'ИНН заказчика', 'Регион заказчика', 'ИНН поставщика',
       'Регион поставщика', 'Идентификатор СТЕ по контракту',
       'Наименование позиции СТЕ', 'Цена за единицу', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35'],
      dtype='object')

In [4]:
contracts_df.shape

(461443, 36)

In [5]:
contracts_df.head()

,Наименование закупки,Количество,Единица измерения,Идентификатор контракта,Способ закупки,Начальная стоимость контракта,Стоимость контракта после заключения,% снижения,Ставка НДС,Дата заключения контракта,...,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Поставка товара,2.0,шт,205193314,Контракт по итогам прямой закупки,25940.0,25940.0,0.0,20%,2025-01-15 07:46:00.660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cols = ['Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35']
corrupted_data = contracts_df[cols].notna().any(axis=1)
contracts_df = contracts_df[~corrupted_data]
contracts_df.drop(columns=['Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35'], inplace=True)

In [7]:
contracts_df

,Наименование закупки,Количество,Единица измерения,Идентификатор контракта,Способ закупки,Начальная стоимость контракта,Стоимость контракта после заключения,% снижения,Ставка НДС,Дата заключения контракта,ИНН заказчика,Регион заказчика,ИНН поставщика,Регион поставщика,Идентификатор СТЕ по контракту,Наименование позиции СТЕ,Цена за единицу
0,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,9718159964,Москва,7729101722,Москва,35927039,Холодильник Haier MSR115 белый,23760.00
1,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,9718159964,Москва,7729101722,Москва,38092313,Печь микроволновая Samsung MS23K3513AS/BW 800 Вт,13860.00
2,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,9718159964,Москва,7729101722,Москва,26233360,"Чайник электрический Tefal KI 760D 1,7 л",6939.90
3,Поставка кухонного бытового оборудования для о...,1.0,шт,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,9718159964,Москва,7729101722,Москва,34993309,Пурифайер M30-U4L silver+SS,26532.00
4,Поставка товара,2.0,шт,205193314,Контракт по итогам прямой закупки,25940.00,25940.00,0.000000,20%,2025-01-15 07:46:00.660,5948044696,Пермский край,5905053375,Пермский край,23887712,Оперативная память Patriot DDR4 8Gb 2666MHz pc...,2370.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461438,Поставка запасных частей для системы вентиляци...,1.0,шт,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,7726269678,Москва,402817987406,Калужская область,39172328,Преобразователь частоты Инстарт LCI-G5.5/P7.5-4B,29582.75
461439,Поставка запасных частей для системы вентиляци...,5.0,шт,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,7726269678,Москва,402817987406,Калужская область,35657481,Ремень клиновой CONTITECH SPA 2240,1699.66
461440,Поставка баков для воды для обеспечения готов...,212.0,шт,213291692,Контракт по итогам котировочной сессии,585756.00,582826.16,0.500181,Без НДС,2025-12-30 00:00:00.000,7751335162,Москва,503618542100,Московская область,36160734,Бак для питьевой воды 200 литров,2749.18
461441,Поставка тележек и контейнеров для сбора мусора,20.0,шт,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,7704880121,Москва,5040120007,Московская область,38536319,Контейнер для мусора KSC 120 зелёный/серый 120 л,7462.50
461442,Поставка тележек и контейнеров для сбора мусора,20.0,шт,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,7704880121,Москва,5040120007,Московская область,38532632,Тележка для сбора мусора Динамика плюс См-02 ч...,14925.00

In [8]:
dropped = contracts_df[contracts_df.isna().any(axis=1)]
# print(contracts_df.shape)
# print(dropped.shape)
dropped

,Наименование закупки,Количество,Единица измерения,Идентификатор контракта,Способ закупки,Начальная стоимость контракта,Стоимость контракта после заключения,% снижения,Ставка НДС,Дата заключения контракта,ИНН заказчика,Регион заказчика,ИНН поставщика,Регион поставщика,Идентификатор СТЕ по контракту,Наименование позиции СТЕ,Цена за единицу
27330,Поставка лекарственного препарата (Пэгинтерфер...,1800.0,NaN,205887363,Контракт по итогам конкурентной процедуры,57816.0,57816.0,0.0,10%,2025-02-05 00:00:00.000,7714338609,Москва,7106526780,Москва,17332371,ПегАльтевир лиоф для п/к введения 150мкг фл ко...,32.12

In [9]:
contracts_df.drop_duplicates(inplace=True)
contracts_df.drop(columns=["Единица измерения", "ИНН заказчика", "ИНН поставщика"], inplace=True)

In [10]:
contracts_df = contracts_df.rename(columns={
    "Идентификатор контракта": "contract_id",
    "Наименование закупки": "purchase_name",
    "Способ закупки": "purchase_type",
    "Регион заказчика": "customer_region",
    "Регион поставщика": "supplier_region",
    "Количество": "quantity",
    "Начальная стоимость контракта": "initial_contract_price",
    "Стоимость контракта после заключения": "final_contract_price",
    "% снижения": "discount_percent",
    "Ставка НДС": "nds_rate",
    "Дата заключения контракта": "contract_date",
    "Идентификатор СТЕ по контракту": "CTE_id",
    "Наименование позиции СТЕ": "CTE_name",
    "Цена за единицу": "unit_price",
})

In [11]:
contracts_df.head()

,purchase_name,quantity,contract_id,purchase_type,initial_contract_price,final_contract_price,discount_percent,nds_rate,contract_date,customer_region,supplier_region,CTE_id,CTE_name,unit_price
0,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,Москва,Москва,35927039,Холодильник Haier MSR115 белый,23760.0
1,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,Москва,Москва,38092313,Печь микроволновая Samsung MS23K3513AS/BW 800 Вт,13860.0
2,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,Москва,Москва,26233360,"Чайник электрический Tefal KI 760D 1,7 л",6939.9
3,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.9,71091.9,0.0,20%,2025-12-01 14:32:09.307,Москва,Москва,34993309,Пурифайер M30-U4L silver+SS,26532.0
4,Поставка товара,2.0,205193314,Контракт по итогам прямой закупки,25940.0,25940.0,0.0,20%,2025-01-15 07:46:00.660,Пермский край,Пермский край,23887712,Оперативная память Patriot DDR4 8Gb 2666MHz pc...,2370.0

In [12]:
cte_ids_contracts = set(contracts_df['CTE_id'].unique())

In [ ]:
cte_ids_contracts = set(contracts_df['CTE_id'].unique())
cte_df = pd.read_csv("../../data/prep/CTE.csv")
cte_ids_ctes = set(cte_df['CTE_id'].unique())
if cte_ids_contracts == cte_ids_ctes:
    print("ПОбеда")

In [19]:
print(list(cte_ids_ctes)[:10])
print(list(cte_ids_contracts)[:10])

[np.int64(36175873), np.int64(38797313), np.int64(38797316), np.int64(38797317), np.int64(37748743), np.int64(34078728), np.int64(37748744), np.int64(37748746), np.int64(38797323), np.int64(37748749)]
[np.int64(38797313), np.int64(36175873), np.int64(38797316), np.int64(38797317), np.int64(37748743), np.int64(34078728), np.int64(37748744), np.int64(37748746), np.int64(38797323), np.int64(37748749)]

In [21]:
# 1. Читаем CTE и берём множество валидных id
cte_df = pd.read_csv("../../data/prep/CTE.csv")
valid_cte_ids = set(cte_df["CTE_id"].unique())

# 2. Фильтруем contracts_df, оставляя только те строки,
#    у которых CTE_id присутствует в CTE.csv
contracts_df = contracts_df[contracts_df["CTE_id"].isin(valid_cte_ids)]

In [23]:
contracts_df.to_csv("../../data/prep/contracts.csv")

In [2]:
import pandas as pd

cte_df = pd.read_csv("../../data/prep/CTE.csv")

print(cte_df["characteristics"])

0         Количество в упаковке:30.00000;Толщина, мкм:50...
1         Цвет:черный;Ширина:470.00000;Количество рулоно...
2         Количество в упаковке:10.00000;Цвет:черный;Тол...
3         Максимальная рабочая температура:50.00000;Коли...
4         Концентрация аналита в наибольшей калибровочно...
                                ...
244479    Ширина:65.00000;Комплектация:Комплект прокладо...
244480    Наличие вкусовых компонентов:Нет;Вид молочного...
244481    Материал трубы:полипропилен;Вид товара:Труба;Д...
244482    Назначение:пшеничная хлебопекарная;Тарная упак...
244483    Температура поверхности клейма:550-600 °С;Вес:...
Name: characteristics, Length: 244484, dtype: object

In [5]:
import pandas as pd

cte = pd.read_csv("../../data/prep/CTE.csv")
contracts = pd.read_csv("../../data/prep/contracts.csv")

In [6]:
cte

,CTE_id,CTE_name,category,manufacturer,characteristics
0,34863000,Мусорные пакеты 35л,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,"Количество в упаковке:30.00000;Толщина, мкм:50..."
1,20647780,Пакеты для мусора,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,Цвет:черный;Ширина:470.00000;Количество рулоно...
2,34865337,Мусорные пакеты 240л,Пакеты полимерные,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СПРИН...,Количество в упаковке:10.00000;Цвет:черный;Тол...
3,38669978,"Радиостанция носимая аналоговая Шеврон, ""АЙТИ-...",Радиостанции цифровые,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""АЙТИ...",Максимальная рабочая температура:50.00000;Коли...
4,38515747,Набор реагентов для иммуноферментного определе...,Наборы реактивов/реагентов,"ООО ""ХЕМА""",Концентрация аналита в наибольшей калибровочно...
...,...,...,...,...,...
244479,39163435,Гофра для раковины EWRIKA 85001 85036-750 40 м...,Удлинители гофрированные для оборудования сант...,EWRIKA,Ширина:65.00000;Комплектация:Комплект прокладо...
244480,39163497,"Творог Б.Ю. Александров 9%, 180г",Творог,Б.Ю. АЛЕКСАНДРОВ,Наличие вкусовых компонентов:Нет;Вид молочного...
244481,39165297,"Труба VALFEX OPTIMA ф110, с раструбом, L=0.25 ...",Детали и фитинги трубопроводов из полимеров,VALFEX OPTIMA,Материал трубы:полипропилен;Вид товара:Труба;Д...
244482,1374499,Мука пшеничная Макфа весовая,Мука пшеничная хлебопекарная,"АО ""Макфа""",Назначение:пшеничная хлебопекарная;Тарная упак...
244483,23651430,Устройство для клеймения шин Ш-309,Приборы для клеймения (маркировки) шин,ООО«ТехСервисСнаб»,Температура поверхности клейма:550-600 °С;Вес:...

In [7]:
contracts

,purchase_name,quantity,contract_id,purchase_type,initial_contract_price,final_contract_price,discount_percent,nds_rate,contract_date,customer_region,supplier_region,CTE_id,CTE_name,unit_price
0,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,Москва,Москва,35927039,Холодильник Haier MSR115 белый,23760.00
1,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,Москва,Москва,38092313,Печь микроволновая Samsung MS23K3513AS/BW 800 Вт,13860.00
2,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,Москва,Москва,26233360,"Чайник электрический Tefal KI 760D 1,7 л",6939.90
3,Поставка кухонного бытового оборудования для о...,1.0,204746787,Контракт по итогам котировочной сессии,71091.90,71091.90,0.000000,20%,2025-12-01 14:32:09.307,Москва,Москва,34993309,Пурифайер M30-U4L silver+SS,26532.00
4,Поставка товара,2.0,205193314,Контракт по итогам прямой закупки,25940.00,25940.00,0.000000,20%,2025-01-15 07:46:00.660,Пермский край,Пермский край,23887712,Оперативная память Patriot DDR4 8Gb 2666MHz pc...,2370.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460744,Поставка запасных частей для системы вентиляци...,1.0,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,Москва,Калужская область,39172328,Преобразователь частоты Инстарт LCI-G5.5/P7.5-4B,29582.75
460745,Поставка запасных частей для системы вентиляци...,5.0,213291631,Контракт по итогам котировочной сессии,44467.02,42910.50,3.500392,5%,2025-12-30 00:00:00.000,Москва,Калужская область,35657481,Ремень клиновой CONTITECH SPA 2240,1699.66
460746,Поставка баков для воды для обеспечения готов...,212.0,213291692,Контракт по итогам котировочной сессии,585756.00,582826.16,0.500181,Без НДС,2025-12-30 00:00:00.000,Москва,Московская область,36160734,Бак для питьевой воды 200 литров,2749.18
460747,Поставка тележек и контейнеров для сбора мусора,20.0,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,Москва,Московская область,38536319,Контейнер для мусора KSC 120 зелёный/серый 120 л,7462.50
460748,Поставка тележек и контейнеров для сбора мусора,20.0,213301644,Контракт по итогам котировочной сессии,517500.00,447750.00,13.478261,5%,2025-12-30 00:00:00.000,Москва,Московская область,38532632,Тележка для сбора мусора Динамика плюс См-02 ч...,14925.00